import type { StdTableColumn } from '@/modules/Shared/components/std';
import type {
  ReportAnatomyStep,
  UiCatalogEntry,
  UiViewPattern,
} from '../types/uiStandardsTypes';

const sharedSource = '@/modules/Shared/components';
const picSource = '@/modules/PIC';

export const uiCatalogEntries: UiCatalogEntry[] = [
  {
    id: 'std-page-header',
    name: 'StdPageHeader',
    category: 'Estructura',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdPageHeader.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Encabezado operativo con contexto, título, descripción, metadatos y acciones.',
    useWhen: ['Vistas administrativas', 'CRUDs', 'Flujos operativos con una acción principal'],
    avoidWhen: ['El módulo ya tiene un encabezado específico aprobado', 'El bloque es una subsección interna'],
    props: [
      { name: 'title', type: 'string', description: 'Título principal de la vista.', required: true },
      { name: 'eyebrow', type: 'string', description: 'Contexto corto sobre el título.' },
      { name: 'description', type: 'string', description: 'Propósito operativo de la vista.' },
      { name: 'icon', type: 'string', description: 'Clases Font Awesome.' },
      { name: 'meta', type: 'string', description: 'Dato compacto de alcance o estado.' },
    ],
    slots: [{ name: 'actions', type: 'slot', description: 'Acciones de encabezado.' }],
    states: ['default', 'con acciones', 'con metadata'],
    responsive: ['Acciones debajo del contenido en espacios reducidos', 'Descripción limitada a una longitud escaneable'],
    accessibility: ['Mantener un único h1 por vista', 'Iconos de acciones con nombre accesible'],
    relatedEntries: ['std-section', 'report-anatomy'],
    examples: [{
      title: 'Encabezado administrativo',
      description: 'Contexto, propósito y acción sin agregar una tarjeta decorativa adicional.',
      code: `<StdPageHeader
  eyebrow="Operación / Catálogo"
  title="Gestión de artículos"
  description="Consulta y administra la información disponible."
  icon="fa-solid fa-box"
/>`,
    }],
  },
  {
    id: 'std-section',
    name: 'StdSection',
    category: 'Estructura',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdSection.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Sección reusable para agrupar una tarea o conjunto coherente de información.',
    useWhen: ['Paneles operativos', 'Bloques con título y contenido relacionado'],
    avoidWhen: ['Crearía una tarjeta dentro de otra sin función', 'Solo se necesita separación tipográfica'],
    props: [
      { name: 'title', type: 'string', description: 'Título de la sección.', required: true },
      { name: 'density', type: "'normal' | 'compact'", description: 'Densidad del panel.', defaultValue: 'normal' },
    ],
    slots: [{ name: 'default', type: 'slot', description: 'Contenido de la sección.' }],
    states: ['normal', 'compact'],
    responsive: ['Padding mobile-first', 'Contenido decide su propio layout'],
    accessibility: ['El título establece la jerarquía de la sección'],
    relatedEntries: ['std-page-header'],
    examples: [{ title: 'Sección compacta', description: 'Útil en paneles laterales o herramientas densas.', code: '<StdSection title="Resumen" density="compact">...</StdSection>' }],
  },
  {
    id: 'std-button',
    name: 'StdButton',
    category: 'Controles',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdButton.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Botón consistente para acciones primarias, secundarias, destructivas y ghost.',
    useWhen: ['Acciones explícitas de usuario', 'Toolbars', 'Confirmaciones'],
    avoidWhen: ['Navegación que debe ser un enlace', 'Acciones sin etiqueta ni aria-label'],
    props: [
      { name: 'variant', type: "'primary' | 'secondary' | 'danger' | 'ghost'", description: 'Jerarquía semántica.', defaultValue: 'secondary' },
      { name: 'size', type: "'sm' | 'md' | 'icon'", description: 'Tamaño del control.', defaultValue: 'md' },
      { name: 'icon', type: 'string', description: 'Clases Font Awesome.' },
      { name: 'disabled', type: 'boolean', description: 'Bloquea interacción.', defaultValue: 'false' },
    ],
    events: [{ name: 'click', type: 'MouseEvent', description: 'Interacción del botón.' }],
    states: ['default', 'hover', 'focus', 'active', 'disabled'],
    responsive: ['Puede ocupar el ancho disponible en mobile mediante class'],
    accessibility: ['Los botones icon-only requieren aria-label', 'No usar disabled como sustituto de una explicación'],
    relatedEntries: ['std-filter-panel', 'std-alert'],
    examples: [{ title: 'Acción primaria', description: 'Un solo CTA dominante por bloque.', code: '<StdButton variant="primary" icon="fa-solid fa-check">Guardar</StdButton>' }],
  },
  {
    id: 'std-alert',
    name: 'StdAlert',
    category: 'Feedback',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdAlert.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Mensaje persistente para información, éxito, advertencia o error.',
    useWhen: ['Errores recuperables', 'Advertencias de negocio', 'Confirmación persistente'],
    avoidWhen: ['Feedback efímero que corresponde a un toast', 'Decoración sin mensaje operativo'],
    props: [
      { name: 'title', type: 'string', description: 'Resumen del mensaje.', required: true },
      { name: 'description', type: 'string', description: 'Detalle y siguiente acción.' },
      { name: 'tone', type: "'info' | 'success' | 'warning' | 'danger'", description: 'Semántica del mensaje.', defaultValue: 'info' },
    ],
    states: ['info', 'success', 'warning', 'danger'],
    responsive: ['Icono y texto conservan una lectura vertical compacta'],
    accessibility: ['El tono visual no sustituye el texto', 'Mensajes dinámicos críticos requieren live region en el consumidor'],
    relatedEntries: ['std-button'],
    examples: [{ title: 'Error recuperable', description: 'Explica el problema y la acción esperada.', code: '<StdAlert tone="danger" title="No fue posible cargar" description="Reintenta la consulta." />' }],
  },
  {
    id: 'std-kpi-card',
    name: 'StdKpiCard',
    category: 'Datos',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdKpiCard.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Indicador con valor principal, contexto, tendencia e icono opcional.',
    useWhen: ['Resumen ejecutivo', 'Monitoreo de pocas métricas comparables'],
    avoidWhen: ['El valor necesita explicación extensa', 'Se muestran demasiados indicadores sin prioridad'],
    props: [
      { name: 'label', type: 'string', description: 'Nombre de la métrica.', required: true },
      { name: 'value', type: 'string', description: 'Valor formateado.', required: true },
      { name: 'trend', type: "'up' | 'down' | 'flat'", description: 'Dirección visual.' },
      { name: 'tone', type: "'brand' | 'success' | 'warning' | 'info' | 'neutral'", description: 'Tono semántico.' },
    ],
    states: ['neutral', 'positivo', 'advertencia', 'informativo'],
    responsive: ['Grid en desktop', 'Carrusel horizontal o apilado en mobile cuando el espacio lo exige'],
    accessibility: ['La tendencia debe expresarse también con texto'],
    relatedEntries: ['report-anatomy'],
    examples: [{ title: 'KPI con comparativo', description: 'Valor, unidad y comparación explícita.', code: '<StdKpiCard label="Venta neta" value="$24.5M" detail="+8.2% vs anterior" trend="up" />' }],
  },
  {
    id: 'std-data-table',
    name: 'StdDataTable',
    category: 'Datos',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdDataTable.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Tabla operativa con ordenamiento, selección, acciones y representación mobile.',
    useWhen: ['Listados administrativos', 'Resultados tabulares sin jerarquía específica'],
    avoidWhen: ['Matrices complejas', 'Edición jerárquica', 'Drill-down que necesita una tabla dedicada'],
    props: [
      { name: 'columns', type: 'StdTableColumn[]', description: 'Columnas visibles.', required: true },
      { name: 'rows', type: 'Record<string, unknown>[]', description: 'Filas del listado.', required: true },
      { name: 'loading', type: 'boolean', description: 'Muestra skeleton.' },
      { name: 'selectable', type: 'boolean', description: 'Habilita selección.' },
      { name: 'selectedKeys', type: '(string | number)[]', description: 'Identificadores seleccionados.' },
      { name: 'rowKey', type: 'string', description: 'Campo identificador de cada fila.', defaultValue: 'id' },
      { name: 'showActions', type: 'boolean', description: 'Muestra la columna de acciones.', defaultValue: 'true' },
      { name: 'actions', type: "('view' | 'edit')[]", description: 'Acciones disponibles por fila.', defaultValue: "['view', 'edit']" },
      { name: 'sortKey', type: 'string', description: 'Columna ordenada actualmente.' },
      { name: 'sortDirection', type: "'asc' | 'desc'", description: 'Dirección del ordenamiento.' },
      { name: 'emptyTitle', type: 'string', description: 'Título del estado vacío.' },
      { name: 'emptyDescription', type: 'string', description: 'Explicación del estado vacío.' },
    ],
    slots: [
      { name: 'cell-[columnKey]', type: 'slot', description: 'Personaliza una columna sin reemplazar la tabla completa.' },
    ],
    events: [
      { name: 'sort', type: 'string', description: 'Columna solicitada.' },
      { name: 'select-row', type: 'string | number', description: 'Identificador seleccionado.' },
      { name: 'row-action', type: "('view' | 'edit', row)", description: 'Acción sobre fila.' },
    ],
    states: ['loading', 'empty', 'data', 'selected'],
    responsive: ['Tabla en md+', 'Cards densas en mobile'],
    accessibility: ['Headers descriptivos', 'Acciones con nombre accesible', 'Selección disponible por teclado'],
    relatedEntries: ['pic-data-table-example', 'pic-projection-table-example'],
    examples: [{ title: 'Listado estándar', description: 'Tabla general reusable; las matrices pueden mantener implementación específica.', code: '<StdDataTable :columns="columns" :rows="rows" />' }],
  },
  {
    id: 'std-switch',
    name: 'StdSwitch',
    category: 'Controles',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdSwitch.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Control binario para activar o desactivar una preferencia con respuesta inmediata.',
    useWhen: ['Preferencias booleanas', 'Estados reversibles que se aplican al cambiar'],
    avoidWhen: ['Confirmar una acción', 'Elegir entre más de dos alternativas'],
    props: [
      { name: 'modelValue', type: 'boolean', description: 'Estado controlado.', required: true },
      { name: 'label', type: 'string', description: 'Etiqueta visible del control.' },
      { name: 'disabled', type: 'boolean', description: 'Impide interacción.' },
    ],
    events: [{ name: 'update:modelValue', type: 'boolean', description: 'Solicita actualizar el estado.' }],
    states: ['activo', 'inactivo', 'disabled'],
    responsive: ['Conserva etiqueta y control en una sola línea cuando hay espacio'],
    accessibility: ['Nombre accesible', 'Estado expresado mediante el control nativo'],
    relatedEntries: ['std-button'],
    examples: [{
      title: 'Preferencia binaria',
      description: 'La vista conserva el estado y la persistencia.',
      code: '<StdSwitch v-model="notificationsEnabled" label="Notificaciones" />',
    }],
  },
  {
    id: 'filter-dropdown',
    name: 'FilterDropdown',
    category: 'Filtros',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/FilterDropdown.vue`,
    importPath: '@/modules/Shared/components/FilterDropdown.vue',
    description: 'Selector filtrable simple o múltiple utilizado por los filtros de PIC.',
    useWhen: ['Catálogos acotados', 'Selección múltiple', 'Filtros dependientes con loading'],
    avoidWhen: ['Búsqueda remota paginada', 'Miles de opciones cargadas de una vez'],
    props: [
      { name: 'options', type: 'string[]', description: 'Opciones disponibles.', required: true },
      { name: 'modelValue', type: 'string[]', description: 'Selección actual.', required: true },
      { name: 'multiple', type: 'boolean', description: 'Permite múltiples valores.', defaultValue: 'true' },
      { name: 'loading', type: 'boolean', description: 'Bloquea y muestra progreso.' },
      { name: 'density', type: "'default' | 'compact'", description: 'Densidad del control.', defaultValue: 'default' },
    ],
    events: [
      { name: 'update:modelValue', type: 'string[]', description: 'Actualiza selección.' },
      { name: 'change', type: 'void', description: 'Notifica cambio para cascadas.' },
      { name: 'open-change', type: 'boolean', description: 'Permite coordinar overlays.' },
    ],
    states: ['empty', 'selected', 'open', 'searching', 'loading', 'disabled'],
    responsive: ['Ocupa el ancho de su grupo', 'Overlay sobre el panel sin recortar opciones'],
    accessibility: ['Listbox con selección declarada', 'Escape cierra búsqueda', 'Estado expandido disponible'],
    relatedEntries: ['std-filter-panel', 'std-filter-group', 'pic-filters-example'],
    examples: [{
      title: 'Filtro dependiente',
      description: 'Limpia la selección cuando cambie su filtro padre y muestra carga solo mientras se actualizan las opciones.',
      code: `<FilterDropdown
  density="compact"
  label="Jefatura"
  :options="jefaturas"
  v-model="selectedJefaturas"
  :loading="loadingJefaturas"
  :disabled="jefaturas.length === 0"
/>`,
    }],
  },
  {
    id: 'std-filter-panel',
    name: 'StdFilterPanel',
    category: 'Filtros',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdFilterPanel.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Panel colapsable con resumen, estado y acciones consistentes para aplicar o limpiar filtros.',
    useWhen: ['Reportes con filtros aplicados mediante CTA', 'Paneles con grupos y cascadas'],
    avoidWhen: ['Un único filtro inline', 'Filtros live sin una acción de aplicar'],
    props: [
      { name: 'collapsed', type: 'boolean', description: 'Estado de expansión.', required: true },
      { name: 'activeCount', type: 'number', description: 'Número de dimensiones activas.', required: true },
      { name: 'status', type: "'idle' | 'dirty' | 'loading' | 'ready' | 'error'", description: 'Estado del reporte.', required: true },
      { name: 'summary', type: 'string', description: 'Resumen visible al colapsar.' },
      { name: 'canReset', type: 'boolean', description: 'Muestra acción de limpiar.', defaultValue: 'true' },
    ],
    slots: [
      { name: 'default', type: 'slot', description: 'Grupos de filtros.' },
      { name: 'mobile-actions', type: 'slot', description: 'Acciones compactas adyacentes.' },
      { name: 'status-detail', type: 'slot', description: 'Explicación adicional del estado.' },
      { name: 'actions-before', type: 'slot', description: 'Acciones específicas antes del CTA.' },
      { name: 'actions-after', type: 'slot', description: 'Acciones específicas posteriores.' },
    ],
    events: [
      { name: 'update:collapsed', type: 'boolean', description: 'Solicita expandir o colapsar.' },
      { name: 'apply', type: 'void', description: 'Solicita aplicar el borrador.' },
      { name: 'reset', type: 'void', description: 'Solicita restablecer filtros permitidos.' },
    ],
    states: ['idle', 'dirty', 'loading', 'ready', 'error', 'collapsed', 'expanded'],
    responsive: ['Header compacto siempre visible', 'Contenido scrollable en mobile', 'Hasta cinco grupos en desktop amplio'],
    accessibility: ['Estado expandido en el botón', 'Eventos sin lógica de negocio oculta'],
    relatedEntries: ['std-filter-group', 'filter-dropdown', 'pic-filters-example'],
    examples: [{
      title: 'Panel con aplicación explícita',
      description: 'Mantén el borrador visible y actualiza los resultados únicamente al usar la acción principal.',
      code: `<StdFilterPanel
  v-model:collapsed="collapsed"
  :active-count="activeCount"
  :status="filtersDirty ? 'dirty' : 'ready'"
  @apply="generateReport"
  @reset="resetFilters"
>
  <StdFilterGroup title="Comercial">...</StdFilterGroup>
</StdFilterPanel>`,
    }],
  },
  {
    id: 'std-filter-group',
    name: 'StdFilterGroup',
    category: 'Filtros',
    scope: 'shared',
    maturity: 'stable',
    source: `${sharedSource}/std/StdFilterGroup.vue`,
    importPath: '@/modules/Shared/components/std',
    description: 'Grupo visual de filtros con encabezado y colapso mobile.',
    useWhen: ['Agrupar filtros por significado', 'Paneles con más de tres dimensiones'],
    avoidWhen: ['Solo hay uno o dos filtros', 'El agrupamiento no comunica relación'],
    props: [
      { name: 'title', type: 'string', description: 'Nombre semántico del grupo.', required: true },
      { name: 'icon', type: 'string', description: 'Clases Font Awesome.' },
      { name: 'description', type: 'string', description: 'Contexto opcional del grupo.' },
      { name: 'defaultOpen', type: 'boolean', description: 'Estado inicial mobile.', defaultValue: 'true' },
    ],
    slots: [{ name: 'default', type: 'slot', description: 'Campos del grupo.' }],
    states: ['mobile abierto', 'mobile cerrado', 'desktop visible'],
    responsive: ['Acordeón en mobile', 'Contenido siempre visible desde md'],
    accessibility: ['Botón con aria-expanded', 'Título describe la relación entre campos'],
    relatedEntries: ['std-filter-panel', 'filter-dropdown'],
    examples: [{ title: 'Grupo comercial', description: 'Agrupa campos relacionados y limpia los descendientes cuando cambie una selección padre.', code: '<StdFilterGroup title="Comercial" icon="fa-solid fa-briefcase">...</StdFilterGroup>' }],
  },
  {
    id: 'pic-dashboard-example',
    name: 'Composición de reporte analítico',
    category: 'Reportes',
    scope: 'module-example',
    maturity: 'stable',
    source: `${picSource}/views/PicDashboardView.vue`,
    description: 'Composición completa con contexto, filtros, resultados, KPIs, gráficas, tablas y herramientas.',
    useWhen: ['Diseñar o revisar un reporte', 'Definir jerarquía entre filtros, KPIs, gráficas y tablas'],
    avoidWhen: ['La vista no presenta resultados analíticos', 'Agregar bloques que no responden a una necesidad del reporte'],
    states: ['inicial', 'generando', 'resultados', 'exportación', 'asistencia'],
    responsive: ['Acciones y filtros compactos en mobile', 'Reporte denso en desktop', 'Herramientas laterales en pantallas amplias'],
    accessibility: ['Jerarquía visible', 'Acciones con etiquetas', 'Contenido disponible sin depender solo del color'],
    relatedEntries: ['pic-filters-example', 'pic-grid-example', 'report-anatomy'],
    examples: [{ title: 'Recorrido de lectura', description: 'Ordena contexto, filtros, resultados y detalle para que la siguiente acción sea evidente.' }],
  },
  {
    id: 'pic-filters-example',
    name: 'Filtros avanzados de reporte',
    category: 'Reportes',
    scope: 'module-example',
    maturity: 'stable',
    source: `${picSource}/components/PicFilters.vue`,
    description: 'Panel de filtros colapsable con cascadas, restricciones de perfil y aplicación explícita.',
    useWhen: ['Diseñar filtros para reportes', 'Modelar cascadas comercial o producto'],
    avoidWhen: ['Solo existe un filtro sencillo', 'Los resultados deben actualizarse inmediatamente con cada cambio'],
    states: ['colapsado', 'expandido', 'dirty', 'loading', 'ready', 'error', 'locked'],
    responsive: ['Acordeones en mobile', 'Grid por grupos en desktop', 'Footer de acciones visible'],
    accessibility: ['Bloqueos explicados', 'Estado y selección expresados con texto'],
    relatedEntries: ['std-filter-panel', 'std-filter-group', 'filter-dropdown'],
    examples: [{ title: 'Comportamiento esperado', description: 'El padre limpia descendientes, cada campo muestra su carga y las restricciones sobreviven al reset.' }],
  },
  {
    id: 'pic-grid-example',
    name: 'Panel analítico',
    category: 'Gráficas',
    scope: 'module-example',
    maturity: 'stable',
    source: `${picSource}/components/PicGrid.vue`,
    description: 'Composición para relacionar gráficas, tablas, widgets dinámicos y desgloses.',
    useWhen: ['Diseñar una composición analítica', 'Relacionar resumen y detalle'],
    avoidWhen: ['Todas las visualizaciones compiten por atención', 'El orden no responde a la pregunta analítica'],
    states: ['datos', 'desglose cerrado', 'desglose abierto', 'print'],
    responsive: ['Dos columnas cuando hay espacio', 'Una columna en espacios reducidos'],
    accessibility: ['Títulos y unidades legibles', 'Controles del desglose disponibles por teclado'],
    relatedEntries: ['pic-echart-example', 'pic-data-table-example'],
    examples: [{ title: 'Libertad analítica', description: 'El tipo, orden y comportamiento de las gráficas pertenece a la pregunta del módulo.' }],
  },
  {
    id: 'pic-echart-example',
    name: 'Gráfica interactiva',
    category: 'Gráficas',
    scope: 'module-example',
    maturity: 'stable',
    source: `${picSource}/components/charts/PicEChart.vue`,
    description: 'Gráfica con título, unidades, tooltip y controles de interacción.',
    useWhen: ['Revisar la calidad visual de una gráfica interactiva'],
    avoidWhen: ['La comparación se entiende mejor en una tabla', 'La interacción no agrega información útil'],
    states: ['default', 'interactivo', 'print'],
    responsive: ['Redimensiona con su contenedor'],
    accessibility: ['Título visible', 'Unidades y tooltip comprensibles'],
    relatedEntries: ['pic-grid-example'],
    examples: [{ title: 'Ejemplo de calidad', description: 'Las visualizaciones conservan libertad de librería, layout, interacción y drill-down.' }],
  },
  {
    id: 'pic-data-table-example',
    name: 'Tabla analítica',
    category: 'Tablas',
    scope: 'module-example',
    maturity: 'stable',
    source: `${picSource}/components/tables/PicDataTable.vue`,
    description: 'Tabla densa para detalle analítico y comparativos por periodo.',
    useWhen: ['Diseñar tablas analíticas densas', 'Vincular una tabla con gráficas o desgloses'],
    avoidWhen: ['Un listado estándar resuelve la tarea', 'La densidad impide identificar el dato principal'],
    states: ['datos', 'comparativo', 'print'],
    responsive: ['Scroll controlado en matrices', 'Información priorizada por espacio'],
    accessibility: ['Headers claros', 'Unidades en títulos o columnas'],
    relatedEntries: ['std-data-table', 'pic-grid-example'],
    examples: [{ title: 'Tabla especializada', description: 'Adapta columnas, jerarquías e interacción a la forma real de los datos.' }],
  },
  {
    id: 'pic-projection-table-example',
    name: 'Tabla de proyección y desglose',
    category: 'Tablas',
    scope: 'module-example',
    maturity: 'stable',
    source: `${picSource}/components/tables/PicProjectionTable.vue`,
    description: 'Matriz comparativa con totales, columnas temporales, participación y detalle jerárquico bajo demanda.',
    useWhen: ['Comparar periodos y metas', 'Explorar una dimensión mediante drill-down', 'Mantener contexto con columnas fijas'],
    avoidWhen: ['Un listado plano resuelve la tarea', 'El detalle no tiene una jerarquía clara'],
    states: ['colapsada', 'loading', 'vacía', 'datos', 'fila expandida', 'detalle cargando', 'print'],
    responsive: ['Prioriza columnas esenciales en mobile', 'Permite ampliar columnas bajo demanda', 'Primera columna fija en matrices anchas'],
    accessibility: ['El control de expansión indica su estado', 'Totales y unidades se identifican en encabezados', 'El detalle conserva relación visual con su padre'],
    relatedEntries: ['pic-data-table-example', 'std-data-table'],
    examples: [{
      title: 'Jerarquía progresiva',
      description: 'Muestra el resumen primero y carga el detalle únicamente cuando la persona expande una fila.',
    }],
  },
];

export const reportAnatomy: ReportAnatomyStep[] = [
  { number: 1, title: 'Contexto y acciones', description: 'Qué se analiza, alcance y acciones globales.', required: true },
  { number: 2, title: 'Filtros', description: 'Borrador, resumen, cascadas, permisos y aplicación explícita.', required: true },
  { number: 3, title: 'Estado inicial', description: 'Explica cómo generar el primer resultado.', required: true },
  { number: 4, title: 'Encabezado de resultados', description: 'Resultado vigente, actualización y exportación.', required: true },
  { number: 5, title: 'Resumen ejecutivo', description: 'Síntesis narrativa o explicativa cuando agrega valor.', required: false },
  { number: 6, title: 'KPIs', description: 'Pocas métricas jerarquizadas con unidad y comparación.', required: false },
  { number: 7, title: 'Gráficas y tablas', description: 'Evidencia principal con libertad analítica.', required: true },
  { number: 8, title: 'Desgloses', description: 'Drill-downs o detalle progresivo bajo demanda.', required: false },
  { number: 9, title: 'Herramientas', description: 'Exportación, asistencia o acciones específicas.', required: false },
];

export const viewPatterns: UiViewPattern[] = [
  {
    id: 'report',
    name: 'Reporte analítico',
    description: 'Filtros controlados, resultado vigente y relación clara entre resumen y evidencia.',
    icon: 'fa-solid fa-chart-column',
    primaryInformation: 'El resultado y su periodo/alcance.',
    sections: ['Contexto', 'Filtros', 'Estado', 'KPIs', 'Gráficas', 'Tablas', 'Desgloses'],
    recommendedEntries: ['pic-dashboard-example', 'std-filter-panel', 'filter-dropdown', 'std-data-table'],
  },
  {
    id: 'crud',
    name: 'CRUD denso',
    description: 'Búsqueda, tabla, acciones esperadas y edición enfocada.',
    icon: 'fa-solid fa-table-list',
    primaryInformation: 'Registros, estado y acción disponible.',
    sections: ['Encabezado', 'Toolbar', 'Tabla', 'Paginación', 'Modal o drawer'],
    recommendedEntries: ['std-page-header', 'std-button', 'std-data-table', 'std-alert'],
  },
  {
    id: 'workflow',
    name: 'Flujo operativo',
    description: 'Secuencia explícita con estado, validación y confirmación.',
    icon: 'fa-solid fa-route',
    primaryInformation: 'Paso actual y siguiente acción segura.',
    sections: ['Contexto', 'Pasos', 'Trabajo actual', 'Validación', 'Confirmación'],
    recommendedEntries: ['std-page-header', 'std-section', 'std-alert', 'std-button'],
  },
  {
    id: 'upload',
    name: 'Carga y preview',
    description: 'Selección, análisis previo, confirmación y resultado auditable.',
    icon: 'fa-solid fa-file-arrow-up',
    primaryInformation: 'Qué se cargará y qué efecto tendrá.',
    sections: ['Periodo', 'Archivos', 'Preview', 'Advertencias', 'Confirmación', 'Historial'],
    recommendedEntries: ['std-page-header', 'std-section', 'std-alert', 'std-data-table'],
  },
  {
    id: 'configuration',
    name: 'Configuración',
    description: 'Parámetros agrupados, diferencias visibles y guardado explícito.',
    icon: 'fa-solid fa-sliders',
    primaryInformation: 'Valor actual, cambio propuesto y alcance.',
    sections: ['Contexto', 'Navegación local', 'Grupos', 'Estado de cambios', 'Guardar'],
    recommendedEntries: ['std-page-header', 'std-section', 'std-button', 'std-alert'],
  },
];

export const chartQualityChecklist = [
  'El título explica qué se muestra; la unidad está visible.',
  'La visualización responde a la pregunta analítica, no a una plantilla.',
  'La leyenda aparece cuando hay más de una serie o agrupación.',
  'Loading, vacío y error tienen estados explícitos.',
  'Tooltip, contraste y etiquetas siguen siendo legibles.',
  'El layout se adapta a su contenedor y no depende de un ancho fijo.',
  'ECharts y Chart.js siguen permitidos según la complejidad y el contexto existente.',
];

export const tableQualityChecklist = [
  'Columnas y unidades tienen nombres inequívocos.',
  'La densidad permite escanear sin ocultar información crítica.',
  'Loading, vacío, selección y acciones tienen estados visibles.',
  'Las tablas estándar usan StdDataTable cuando su API es suficiente.',
  'Matrices, jerarquías, edición y drill-down pueden conservar tablas específicas.',
  'Mobile usa cards, prioridades o scroll controlado según el tipo de datos.',
  'Las acciones masivas aparecen solo cuando existe una selección.',
  'La paginación informa rango, total y tamaño de página.',
  'La exportación respeta filtros, orden y alcance aplicados.',
  'Las columnas fijas conservan contexto sin ocultar datos al desplazarse.',
  'La edición distingue borrador, validación, guardado y error.',
];

export const tableColumns: StdTableColumn[] = [
  { key: 'id', label: 'ID', sortable: true },
  { key: 'product', label: 'Producto', sortable: true },
  { key: 'status', label: 'Estado', align: 'center' },
  { key: 'amount', label: 'Importe', align: 'right', sortable: true },
];

export const tableRows = [
  { id: 101, product: 'Producto A', status: 'Activo', amount: '$120.00' },
  { id: 102, product: 'Producto B', status: 'Inactivo', amount: '$80.00' },
  { id: 103, product: 'Producto C', status: 'Activo', amount: '$95.50' },
];
